FROM nginx:1.27-bookworm AS web_server

# Apt https
RUN apt-get install apt-transport-https -y
RUN apt-get update -y

# Laravel 11 php 8.2
RUN apt-get install -y php-fpm php-pdo php-mysql php-sqlite3
# RUN apt-get install -y openssl php-cli php-common php-curl php-json php-bcmath php-xml php-mbstring php-intl php-tokenizer php-zip php-gd 

COPY --chown=www-data:www-data --chmod=2775 ./webapp /var/www/html

COPY ./nginx/sock/default.conf /etc/nginx/conf.d/default.conf

COPY ./php/sock/www.conf /etc/php/8.2/fpm/pool.d/www.conf

RUN nginx -t

RUN service php8.2-fpm restart

RUN service nginx restart

# # Install composer
# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# # Install
# RUN composer install

# # Laravel Update
# RUN php artisan config:clear
# RUN php artisan cache:clear
# RUN php artisan migrate
# RUN php artisan storage:link

WORKDIR /var/www/html/public

# USER www-data
# EXPOSE 8000
